baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Cloud Castles'
theme = 'brand-cloud-castles'

googleAnalytics = 'G-1EF7F5FSMP'

[build]
  writeStats = true

[environment]
  HUGO_ENVIRONMENT = "production"

[params]
  description = 'Cloud Castles'
  copyright = "All rights reserved © Cloudcastles"
  author = 'Cloud Castles'
  keywords = 'Cloud Castles'
  twitter = 'Cloud Castles'
  github = 'Cloud Castles'
  linkedin = 'https://www.linkedin.com/company/cloudcastles'
  facebook = 'Cloud Castles'
  googleplus = 'Cloud Castles'
  email = 'contact@cloud-castles.com'
  rss = 'Cloud Castles'
  disqusShortname = 'Cloud Castles'
  enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "IaC"
    url = "/iac/"
    weight = 1
  [[menu.main]]
    name = "Sosivio"
    url = "/sosivio/"
    weight = 2
  [[menu.main]]
    name = "Careers"
    url = "/careers/"
    weight = 5
